version: '3'
services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - express-api

  express-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
